/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Historique: typeof import('./src/components/game-logic/Historique.vue')['default']
    HistoriqueLigne: typeof import('./src/components/game-logic/HistoriqueLigne.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LigneEssaie: typeof import('./src/components/game-logic/LigneEssaie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulesModal: typeof import('./src/components/RulesModal.vue')['default']
    SelecteurDifficulte: typeof import('./src/components/SelecteurDifficulte.vue')['default']
  }
}
